# 编译器
CC = E:/Mingw/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/gcc.exe

# 编译选项
CFLAGS = -Wall -O0

# 源文件
SRC = main.c vector.c

# 对应的目标文件
OBJ = $(SRC:.c=.o)

# 可执行文件名称
TARGET = vector.exe

# 默认目标
all: $(TARGET)

# 链接生成可执行文件
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# 编译每个源文件生成目标文件
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# 清理编译生成的文件
ifeq ($(OS),Windows_NT)
    RM = del /Q
else
    RM = rm -f
endif

clean:
	$(RM) $(OBJ) $(TARGET)

# 伪目标，防止和文件同名冲突
.PHONY: all clean